mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('quora.urls',namespace='quora')),
    
    
]

quora/urls.py
"""Defines URL patterns for quora."""

from django.urls import include,path
from . import views

app_name = 'quora'

urlpatterns = [
    # Home page
    path('',views.index, name='index'),

    # Show all tags.
    path('tags',views.tags, name='tags'),

    # All Question in a single tag.
    path('tags/<int:tag_id>/', views.tag, name='tag'),

    # Page for adding a new tag.
    path('new_tag', views.new_tag, name='new_tag'),

    # Page for adding a new question.
    path('new_question',views.new_question, name='new_question'),
    path('new_question/<int:tag_id>/',views.new_question, name='new_question_tag'),

    # Page for showing question and answer.
    path('question/<int:question_id>/', views.question, name='question'),

    # Page for editing questions.
    path('edit_question/<int:question_id>/',views.edit_question,name='edit_question'),

    # Page for answering question.
    path('answer_question/<int:question_id>/', views.answer_question,name='answer_question'),
    

]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView


from . import views

app_name = 'users'

urlpatterns = [
 # Login page
 path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),

 # Logout Page
 path('logout/', views.logout_view, name='logout' ),

 # Registration Page
 path('register/', views.register, name='register'),

]

quora/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tag(models.Model):
    """A Tag linked to a question."""
    text = models.CharField(max_length=30)
    date_added = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=300,null=True,blank=True)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        """Return a string representation of model."""
        return self.text
    
class Question(models.Model):
    """Questions related to a Topic."""
    tag = models.ForeignKey(Tag,on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User,on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'question'
        verbose_name_plural = 'questions'

    def __str__(self):
        """Return String."""
        if len(self.text) > 150:
            return self.text[:150] + "..."
        else:
            return self.text

class Answer(models.Model):
    """Answe to a particular Question."""
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User,on_delete=models.PROTECT)
    rating = models.PositiveIntegerField()

    def __str__(self):
        """Return String Representation."""
        if len(self.text) > 250:
            return self.text[:250] + "..."
        else:
            return self.text



quora/forms.py
from django import forms

from . models import Tag, Question ,Answer


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['text']
        labels = {'text': 'Enter New Tag Name'}

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text','tag']
        initial = {'tag':1}
        labels = {'text':'Enter Question','tag':'Choose Tag'}
        widgets = {'text': forms.Textarea(attrs={'cols':80}),}

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text',]
        labels = {'text':'Your Answer'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}
        

quora/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required

from .models import Tag, Question, Answer
from .forms import TagForm, QuestionForm, AnswerForm

def index(request):
    """The home page for Quora"""
    questions = Question.objects.order_by('-id')
    answers = Answer.objects.order_by('-rating')
    qa = {}
    for q in questions:
        qa[int(q.id)] = 'No Answer.'
        for a in answers:
            if a.question == q:
                qa[int(q.id)] = a.text
                break
    questions = Question.objects.order_by('-date_added')
    context = {'questions':questions,'qa':qa}
    return render(request, 'quora/index.html',context)

def tags(request):
    """Show all tags."""
    tags = Tag.objects.order_by('text')
    context = {'tags': tags}
    return render(request, 'quora/tags.html',context)

def tag(request, tag_id):
    """Show a single tag and all its questions."""
    tag = Tag.objects.get(id=tag_id)
    questions = tag.question_set.order_by('-date_added')
    context = {'tag':tag, 'questions':questions}
    return render(request, 'quora/tag.html', context)

@login_required
def new_tag(request):
    """Add a new tag."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TagForm()
    else:
        # POST data submitted; process data.
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('quora:tags'))
    context = {'form':form}
    return render(request, 'quora/new_tag.html',context)

def question(request, question_id):
    """Show Question With its answers."""
    question = Question.objects.get(id=question_id)
    #answers = Answer.objects.get(question=question)
    answers = question.answer_set.order_by('-rating')
    context = {'question':question, 'answers':answers}
    return render(request, 'quora/question.html', context)



@login_required
def new_question(request, tag_id=1):
    """Adding a new Question to a particular tag."""
    #tag = Tag.objects.get(id=tag_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = QuestionForm()
        form.fields['tag'].initial = tag_id 
    else:
        # POST data submitted; process data.
        form = QuestionForm(data=request.POST)
        if form.is_valid():
            new_question = form.save(commit=False)
            #new_question.tag = tag
            new_question.owner = request.user
            new_question.save()
            return HttpResponseRedirect(reverse('quora:tag',args=[new_question.tag.id]))
    
    context = {'form':form}
    return render(request, 'quora/new_question.html', context)

@login_required
def edit_question(request, question_id):
    """Edit an existing question."""
    question = Question.objects.get(id=question_id)
    tag = question.tag
    if question.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with current entry.
        form = QuestionForm(instance=question)

    else:
        # POST data submitted; process data.
        form = QuestionForm(instance=question, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('quora:tag', args=[tag.id]))
    
    context = {'question': question, 'tag':tag, 'form':form}
    return render(request, 'quora/edit_question.html', context)

@login_required
def answer_question(request, question_id):
    """Answering a particular question."""
    question = Question.objects.get(id=question_id)
    tag = question.tag

    if request.method != 'POST':
        # Initial request; pre-fill form with question and answers.
        form = AnswerForm()

    else:
        # POST data submitted; process data.
        form = AnswerForm(data=request.POST)
        if form.is_valid():
            new_answer = form.save(commit=False)
            new_answer.owner = request.user
            new_answer.rating = 1
            new_answer.question = question
            new_answer.save()
            # change redirect page
            #return HttpResponseRedirect(reverse('quora:index'))
            return HttpResponseRedirect(reverse('quora:question',args=[question_id]))

    context = {'question':question, 'form':form, 'tag':tag}
    return render(request, 'quora/answer_question.html', context)

        

quora/templates/quora/answer_question.html
{% extends 'quora/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h3><strong>{{question.text}}</strong></h3>
{% endblock header %}

{% block content %}
    
	<form action="{% url 'quora:answer_question' question.id %}" method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}
		
		{% buttons %}
 			<button name="submit" class="btn btn-primary">Submit Answer</button>
 		{% endbuttons %}
	</form>
{% endblock content %}

quora/templates/quora/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Quora</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" 
              data-toggle="collapse" data-target="#navbar" 
              aria-expanded="false" aria-controls="navbar">▼
              </button>
              <a class="navbar-brand text-red" href="{% url 'quora:index' %}"> Quora </a>
           </div>
   
   <div id="navbar" class="navbar-collapse collapse">
   <ul class="nav navbar-nav">
   <li><a href="{% url 'quora:tags' %}">Tags</a></li>
    </ul>
   
   <ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <li><a>Hello, {{ user.username.title }}.</a></li>
    <li><a href="{% url 'users:logout' %}">Log Out</a></li>
    {% else %}
    <li><a href="{% url 'users:register' %}">Register</a></li>
    <li><a href="{% url 'users:login' %}">Log In</a></li>
    {% endif %}
   </ul>
    </div><!--/.nav-collapse -->
   
    </div>
   </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
           {% block content %}{% endblock content %}
        </div>
     </div> <!-- /container -->
    </body>
  </html>

quora/templates/quora/base1.html
<p>
    <a href="{% url 'quora:index' %}">Quora</a>-
    <a href="{% url 'quora:tags' %}">Tags</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a> -
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

quora/templates/quora/edit_question.html
{% extends 'quora/base.html' %}

{% block content %}

	<p><a href="{% url 'quora:tag' tag.id %}">{{tag}}</a></p>

	<p>Edit Question :</p>

	<form action="{% url 'quora:edit_question' question.id %}" method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button name="submit">save changes</button>
	</form>
{% endblock content %}

quora/templates/quora/index.html
{% extends "quora/base.html" %}

{% load get_list_index %}

{% block header %}
	<div class="jumbotron text-center">
			<p><h2>Quora - The Questions and Answers Website...</h2></p>
	</div>
	<h4><p class="text-center">Quora lets you asks questions and get the answers from 
			our large community.<br>
			You can also give answers to others questions and help others and also increase our 
			ever incresasing database of knowledge.
	</p></h>
{% endblock header %}

{% block content %}


	<a href="{% url 'quora:new_question' %}"><h3 class="text-center">Add New Question</h3></a>
    {% for question in questions %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
						{{ question.text }}
						<small>
							{{ question.tag}}
						</small>
                
        </h3>
      </div>
      <div class="panel-body">
					<h4>
						{{qa|get_dict_value:question.id}}
						
					</h4>
			</div>
			<div class="panel-body">
					<a href="{% url 'quora:question' question.id %}">See All Answers</a>-
					<a href="{% url 'quora:answer_question' question.id %}">Give Answer</a>
					{% ifequal question.owner request.user %}
                -<a href="{% url 'quora:edit_question' question.id %}">Edit Question</a>
          {% endifequal %}
					<p style="text-align:right;">On {{ question.date_added|date:'M d, Y H:i' }} By {{question.owner.username.title}}</p> 
      </div>
    </div>
   {% empty %}
    There are no questions for this tag yet.
  {% endfor %}


{% endblock content %}

quora/templates/quora/new_question.html
{% extends "quora/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h3><strong>Add a new question.</strong></h3>
{% endblock header %}

{% block content %}

<form action="{% url 'quora:new_question' %}" method='post'>
 {% csrf_token %}
 {% bootstrap_form form %}
	{% buttons %}
 		<button name="submit" class="btn btn-primary">Add Question</button>
 	{% endbuttons %}
 </form>

{% endblock content %}

quora/templates/quora/new_tag.html
{% extends "quora/base.html" %}

{% block header%}
  <h2>Enter a new Tag</h2>
{% endblock header %}

{% block content %}

 <form action="{% url 'quora:new_tag' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit" class="btn">Add Tag</button>
</form>
{% endblock content %}

quora/templates/quora/question.html
{% extends 'quora/base.html' %}

{% block header %}
  <h2><strong>{{question.text}}</strong></h2>
{% endblock header %}

{% block content %}

<h4><p><a href="{% url 'quora:answer_question' question.id %}">Answer Question</a></p></h4>

{% for answer in answers %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
            {{ answer.text }}
            <small>
                {{answer.rating}}
            </small>
        </h3>
      </div>
      <div class="panel-body">
        <p>Upvote-Downvote</p>
        <p class="text-right"> On {{ answer.date_added|date:'M d, Y H:i' }} By {{answer.owner.username.title}}</p>
      </div>
    </div>
        <a href="{% url 'quora:question' question.id %}">see answers</a>
   {% empty %}
    <h4><br>There are no answers for this question yet.</h4>
  {% endfor %}
{% endblock content %}

quora/templates/quora/tag.html
{% extends 'quora/base.html' %}

{% block header %}
 <h1>{{ tag }}</h1>
{% endblock header %}

{% block content %}

 <h4><p><a href="{% url 'quora:new_question_tag' tag.id %}">Add a New Question</a></p></h4>
  <p><h4>Questions:</h4></p>
  
  {% for question in questions %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
            {{ question.text }}
            <small>
                {% ifequal question.owner request.user %}
                <a href="{% url 'quora:edit_question' question.id %}">Edit Question</a>
              {% endifequal %}
            </small>
        </h3>
      </div>
      <div class="panel-body">
          On {{ question.date_added|date:'M d, Y H:i' }} By {{question.owner.username.title}}
      </div>
    </div>
        <a href="{% url 'quora:question' question.id %}">see answers</a>
   {% empty %}
    There are no questions for this tag yet.
  {% endfor %}

{% endblock content %}

quora/templates/quora/tags.html
{% extends "quora/base.html" %}

{% block header %}
 <h2>Tags</h2>
{% endblock header %}

{% block content %}

{% for tag in tags %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>
			<a href="{% url 'quora:tag' tag.id %}">{{ tag.text }}</a>
        </h4>
      </div>
      <div class="panel-body">
        <p>{{tag.description}}</p>
      </div>
    </div>
        
   {% empty %}
    <h4><br>No tags have been added yet.</h4>
  {% endfor %}

<a href="{% url 'quora:new_tag' %}">Add a new tag:</a>

{% endblock content %}